### PR TITLE
Use timezone of vector instead of trying to specify

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Addresses #17

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK Do you know of any reason we wouldn't want to make this change? I believe it is now behaving as expected but wasn't here when this method was being created.

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
@Jeff-Thompson12, can you add a row to the `NEWS.md` file? Otherwise I think this PR is good to go, but maybe you could walk through a scenario with me?

I created some fake data to our starwars example data in the `inst/` folder:
```r
# prep a new data.frame with more diverse data types
starwars2 <- starwars %>%
 mutate_if(~is.numeric(.) && all(Filter(Negate(is.na), .) %% 1 == 0), as.integer) %>%
 mutate_if(~is.character(.) && length(unique(.)) <= 25, as.factor) %>%
 mutate(is_droid = species == "Droid") %>%
 select(name, gender, height, mass, hair_color, eye_color, vehicles, is_droid) %>%
 mutate(dt = as.POSIXct("2023-08-01 10:23:05", origin = "1970-01-01 00:00:00", tz = "EST") + row_number())
```
Which produces the following table with no data when launching `app.R`. That makes sense because if I'm currently located in EDT (the day light savings time version of EST). Once I switch the tz above to "EDT", all the data shows up.

image

Is that what we want to happen? Do we only want to see data as it pertains to the user's time zone instead of the data's timezone?

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK Question: 
Do you think the datetime filter should be representing times corresponding to the time zone of the data or the time zone of the user?

**Comment by Jeff-Thompson12** [comment]
> Which produces the following table with no data when launching `app.R`. That makes sense because if I'm currently located in EDT (the day light savings time version of EST). Once I switch the tz above to "EDT", all the data shows up.

In order to view the changes you will have to build the package based on the PR. I think you can also run `devtools::load_all()`. When you run the app, you should be able to see all the data regardless of which time zone you initialize the datetime field as.

**Review by AARON-CLARK — APPROVED** [review]
Whoops! My mistake. It appears to be working just fine now that I've loaded the pkg.

**Comment by AARON-CLARK** [comment]
Also, did you just answer my question by asking me the same question? 😆 Either way, this PR is ready to go.

image

**Pull request merged**
